// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "chat.proto" (package "chat.v1", syntax proto3)
// tslint:disable
import { ServiceType } from "@protobuf-ts/runtime-rpc";
import type { BinaryWriteOptions } from "@protobuf-ts/runtime";
import type { IBinaryWriter } from "@protobuf-ts/runtime";
import { WireType } from "@protobuf-ts/runtime";
import type { BinaryReadOptions } from "@protobuf-ts/runtime";
import type { IBinaryReader } from "@protobuf-ts/runtime";
import { UnknownFieldHandler } from "@protobuf-ts/runtime";
import type { PartialMessage } from "@protobuf-ts/runtime";
import { reflectionMergePartial } from "@protobuf-ts/runtime";
import { MessageType } from "@protobuf-ts/runtime";
/**
 * 채팅 메시지 정의
 *
 * @generated from protobuf message chat.v1.ChatMessage
 */
export interface ChatMessage {
    /**
     * @generated from protobuf field: string roomid = 1
     */
    roomid: string; // 채팅방 ID
    /**
     * @generated from protobuf field: string username = 2
     */
    username: string; // 사용자 이름
    /**
     * @generated from protobuf field: string message = 3
     */
    message: string; // 메시지 내용
}
/**
 * 방 ID 요청 메시지
 *
 * @generated from protobuf message chat.v1.GetRoomIDRequest
 */
export interface GetRoomIDRequest {
    /**
     * @generated from protobuf field: string my_id = 1
     */
    myId: string; // 내 아이디
    /**
     * @generated from protobuf field: string other_id = 2
     */
    otherId: string; // 대화할 상대방 아이디
}
/**
 * 방 ID 응답 메시지
 *
 * @generated from protobuf message chat.v1.GetRoomIDResponse
 */
export interface GetRoomIDResponse {
    /**
     * @generated from protobuf field: string room_id = 1
     */
    roomId: string; // 계산된 방 ID (예: hun_min)
}
/**
 * [추가] 내 채팅방 목록 요청
 *
 * @generated from protobuf message chat.v1.GetMyRoomsRequest
 */
export interface GetMyRoomsRequest {
    /**
     * @generated from protobuf field: string user_id = 1
     */
    userId: string; // 내 아이디 (로그인한 사용자)
}
/**
 * [추가] 채팅방 정보 구조체
 *
 * @generated from protobuf message chat.v1.ChatRoomInfo
 */
export interface ChatRoomInfo {
    /**
     * @generated from protobuf field: string room_id = 1
     */
    roomId: string;
    /**
     * @generated from protobuf field: string other_user_id = 2
     */
    otherUserId: string; // 상대방 아이디 (프론트에 보여줄 용도)
}
/**
 * [추가] 내 채팅방 목록 응답
 *
 * @generated from protobuf message chat.v1.GetMyRoomsResponse
 */
export interface GetMyRoomsResponse {
    /**
     * @generated from protobuf field: repeated chat.v1.ChatRoomInfo rooms = 1
     */
    rooms: ChatRoomInfo[];
}
// @generated message type with reflection information, may provide speed optimized methods
class ChatMessage$Type extends MessageType<ChatMessage> {
    constructor() {
        super("chat.v1.ChatMessage", [
            { no: 1, name: "roomid", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "username", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 3, name: "message", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ChatMessage>): ChatMessage {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomid = "";
        message.username = "";
        message.message = "";
        if (value !== undefined)
            reflectionMergePartial<ChatMessage>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChatMessage): ChatMessage {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string roomid */ 1:
                    message.roomid = reader.string();
                    break;
                case /* string username */ 2:
                    message.username = reader.string();
                    break;
                case /* string message */ 3:
                    message.message = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChatMessage, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string roomid = 1; */
        if (message.roomid !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.roomid);
        /* string username = 2; */
        if (message.username !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.username);
        /* string message = 3; */
        if (message.message !== "")
            writer.tag(3, WireType.LengthDelimited).string(message.message);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.ChatMessage
 */
export const ChatMessage = new ChatMessage$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRoomIDRequest$Type extends MessageType<GetRoomIDRequest> {
    constructor() {
        super("chat.v1.GetRoomIDRequest", [
            { no: 1, name: "my_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "other_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRoomIDRequest>): GetRoomIDRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.myId = "";
        message.otherId = "";
        if (value !== undefined)
            reflectionMergePartial<GetRoomIDRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRoomIDRequest): GetRoomIDRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string my_id */ 1:
                    message.myId = reader.string();
                    break;
                case /* string other_id */ 2:
                    message.otherId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRoomIDRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string my_id = 1; */
        if (message.myId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.myId);
        /* string other_id = 2; */
        if (message.otherId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.otherId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.GetRoomIDRequest
 */
export const GetRoomIDRequest = new GetRoomIDRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetRoomIDResponse$Type extends MessageType<GetRoomIDResponse> {
    constructor() {
        super("chat.v1.GetRoomIDResponse", [
            { no: 1, name: "room_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetRoomIDResponse>): GetRoomIDResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomId = "";
        if (value !== undefined)
            reflectionMergePartial<GetRoomIDResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetRoomIDResponse): GetRoomIDResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string room_id */ 1:
                    message.roomId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetRoomIDResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string room_id = 1; */
        if (message.roomId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.roomId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.GetRoomIDResponse
 */
export const GetRoomIDResponse = new GetRoomIDResponse$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyRoomsRequest$Type extends MessageType<GetMyRoomsRequest> {
    constructor() {
        super("chat.v1.GetMyRoomsRequest", [
            { no: 1, name: "user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<GetMyRoomsRequest>): GetMyRoomsRequest {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.userId = "";
        if (value !== undefined)
            reflectionMergePartial<GetMyRoomsRequest>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyRoomsRequest): GetMyRoomsRequest {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string user_id */ 1:
                    message.userId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyRoomsRequest, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string user_id = 1; */
        if (message.userId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.userId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.GetMyRoomsRequest
 */
export const GetMyRoomsRequest = new GetMyRoomsRequest$Type();
// @generated message type with reflection information, may provide speed optimized methods
class ChatRoomInfo$Type extends MessageType<ChatRoomInfo> {
    constructor() {
        super("chat.v1.ChatRoomInfo", [
            { no: 1, name: "room_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ },
            { no: 2, name: "other_user_id", kind: "scalar", T: 9 /*ScalarType.STRING*/ }
        ]);
    }
    create(value?: PartialMessage<ChatRoomInfo>): ChatRoomInfo {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.roomId = "";
        message.otherUserId = "";
        if (value !== undefined)
            reflectionMergePartial<ChatRoomInfo>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: ChatRoomInfo): ChatRoomInfo {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* string room_id */ 1:
                    message.roomId = reader.string();
                    break;
                case /* string other_user_id */ 2:
                    message.otherUserId = reader.string();
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: ChatRoomInfo, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* string room_id = 1; */
        if (message.roomId !== "")
            writer.tag(1, WireType.LengthDelimited).string(message.roomId);
        /* string other_user_id = 2; */
        if (message.otherUserId !== "")
            writer.tag(2, WireType.LengthDelimited).string(message.otherUserId);
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.ChatRoomInfo
 */
export const ChatRoomInfo = new ChatRoomInfo$Type();
// @generated message type with reflection information, may provide speed optimized methods
class GetMyRoomsResponse$Type extends MessageType<GetMyRoomsResponse> {
    constructor() {
        super("chat.v1.GetMyRoomsResponse", [
            { no: 1, name: "rooms", kind: "message", repeat: 2 /*RepeatType.UNPACKED*/, T: () => ChatRoomInfo }
        ]);
    }
    create(value?: PartialMessage<GetMyRoomsResponse>): GetMyRoomsResponse {
        const message = globalThis.Object.create((this.messagePrototype!));
        message.rooms = [];
        if (value !== undefined)
            reflectionMergePartial<GetMyRoomsResponse>(this, message, value);
        return message;
    }
    internalBinaryRead(reader: IBinaryReader, length: number, options: BinaryReadOptions, target?: GetMyRoomsResponse): GetMyRoomsResponse {
        let message = target ?? this.create(), end = reader.pos + length;
        while (reader.pos < end) {
            let [fieldNo, wireType] = reader.tag();
            switch (fieldNo) {
                case /* repeated chat.v1.ChatRoomInfo rooms */ 1:
                    message.rooms.push(ChatRoomInfo.internalBinaryRead(reader, reader.uint32(), options));
                    break;
                default:
                    let u = options.readUnknownField;
                    if (u === "throw")
                        throw new globalThis.Error(`Unknown field ${fieldNo} (wire type ${wireType}) for ${this.typeName}`);
                    let d = reader.skip(wireType);
                    if (u !== false)
                        (u === true ? UnknownFieldHandler.onRead : u)(this.typeName, message, fieldNo, wireType, d);
            }
        }
        return message;
    }
    internalBinaryWrite(message: GetMyRoomsResponse, writer: IBinaryWriter, options: BinaryWriteOptions): IBinaryWriter {
        /* repeated chat.v1.ChatRoomInfo rooms = 1; */
        for (let i = 0; i < message.rooms.length; i++)
            ChatRoomInfo.internalBinaryWrite(message.rooms[i], writer.tag(1, WireType.LengthDelimited).fork(), options).join();
        let u = options.writeUnknownFields;
        if (u !== false)
            (u == true ? UnknownFieldHandler.onWrite : u)(this.typeName, message, writer);
        return writer;
    }
}
/**
 * @generated MessageType for protobuf message chat.v1.GetMyRoomsResponse
 */
export const GetMyRoomsResponse = new GetMyRoomsResponse$Type();
/**
 * @generated ServiceType for protobuf service chat.v1.ChatService
 */
export const ChatService = new ServiceType("chat.v1.ChatService", [
    { name: "JoinChat", serverStreaming: true, clientStreaming: true, options: {}, I: ChatMessage, O: ChatMessage },
    { name: "GetRoomID", options: {}, I: GetRoomIDRequest, O: GetRoomIDResponse },
    { name: "GetMyRooms", options: {}, I: GetMyRoomsRequest, O: GetMyRoomsResponse }
]);
