// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "chat.proto" (package "chat.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { ChatService } from "./chat";
import type { GetMyRoomsResponse } from "./chat";
import type { GetMyRoomsRequest } from "./chat";
import type { GetRoomIDResponse } from "./chat";
import type { GetRoomIDRequest } from "./chat";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { ChatMessage } from "./chat";
import type { DuplexStreamingCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * 채팅 서비스 정의
 *
 * @generated from protobuf service chat.v1.ChatService
 */
export interface IChatServiceClient {
    /**
     * 양방향 스트리밍 RPC
     *
     * @generated from protobuf rpc: JoinChat
     */
    joinChat(options?: RpcOptions): DuplexStreamingCall<ChatMessage, ChatMessage>;
    /**
     * 방 ID 발급 API
     *
     * @generated from protobuf rpc: GetRoomID
     */
    getRoomID(input: GetRoomIDRequest, options?: RpcOptions): UnaryCall<GetRoomIDRequest, GetRoomIDResponse>;
    /**
     * [추가] 내 채팅방 목록 조회 API
     *
     * @generated from protobuf rpc: GetMyRooms
     */
    getMyRooms(input: GetMyRoomsRequest, options?: RpcOptions): UnaryCall<GetMyRoomsRequest, GetMyRoomsResponse>;
}
/**
 * 채팅 서비스 정의
 *
 * @generated from protobuf service chat.v1.ChatService
 */
export class ChatServiceClient implements IChatServiceClient, ServiceInfo {
    typeName = ChatService.typeName;
    methods = ChatService.methods;
    options = ChatService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 양방향 스트리밍 RPC
     *
     * @generated from protobuf rpc: JoinChat
     */
    joinChat(options?: RpcOptions): DuplexStreamingCall<ChatMessage, ChatMessage> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChatMessage, ChatMessage>("duplex", this._transport, method, opt);
    }
    /**
     * 방 ID 발급 API
     *
     * @generated from protobuf rpc: GetRoomID
     */
    getRoomID(input: GetRoomIDRequest, options?: RpcOptions): UnaryCall<GetRoomIDRequest, GetRoomIDResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetRoomIDRequest, GetRoomIDResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * [추가] 내 채팅방 목록 조회 API
     *
     * @generated from protobuf rpc: GetMyRooms
     */
    getMyRooms(input: GetMyRoomsRequest, options?: RpcOptions): UnaryCall<GetMyRoomsRequest, GetMyRoomsResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetMyRoomsRequest, GetMyRoomsResponse>("unary", this._transport, method, opt, input);
    }
}
