// @generated by protobuf-ts 2.11.1
// @generated from protobuf file "user.proto" (package "user.v1", syntax proto3)
// tslint:disable
import type { RpcTransport } from "@protobuf-ts/runtime-rpc";
import type { ServiceInfo } from "@protobuf-ts/runtime-rpc";
import { UserService } from "./user";
import type { SearchUsersResponse } from "./user";
import type { SearchUsersRequest } from "./user";
import type { UpdateAvatarResponse } from "./user";
import type { UpdateAvatarRequest } from "./user";
import type { ChangePasswordResponse } from "./user";
import type { ChangePasswordRequest } from "./user";
import type { UpdateProfileResponse } from "./user";
import type { UpdateProfileRequest } from "./user";
import type { GetProfileResponse } from "./user";
import type { GetProfileRequest } from "./user";
import type { SocialLoginResponse } from "./user";
import type { SocialLoginRequest } from "./user";
import type { LoginResponse } from "./user";
import type { LoginRequest } from "./user";
import type { SignUpResponse } from "./user";
import type { SignUpRequest } from "./user";
import type { VerifyPhoneResponse } from "./user";
import type { VerifyPhoneRequest } from "./user";
import type { RequestPhoneVerificationResponse } from "./user";
import type { RequestPhoneVerificationRequest } from "./user";
import type { CheckEmailResponse } from "./user";
import type { CheckEmailRequest } from "./user";
import { stackIntercept } from "@protobuf-ts/runtime-rpc";
import type { CheckUsernameResponse } from "./user";
import type { CheckUsernameRequest } from "./user";
import type { UnaryCall } from "@protobuf-ts/runtime-rpc";
import type { RpcOptions } from "@protobuf-ts/runtime-rpc";
/**
 * ====== 서비스 정의 (명세)======
 *
 * @generated from protobuf service user.v1.UserService
 */
export interface IUserServiceClient {
    /**
     * 중복/인증
     *
     * @generated from protobuf rpc: CheckUsername
     */
    checkUsername(input: CheckUsernameRequest, options?: RpcOptions): UnaryCall<CheckUsernameRequest, CheckUsernameResponse>;
    /**
     * @generated from protobuf rpc: CheckEmail
     */
    checkEmail(input: CheckEmailRequest, options?: RpcOptions): UnaryCall<CheckEmailRequest, CheckEmailResponse>;
    /**
     * @generated from protobuf rpc: RequestPhoneVerification
     */
    requestPhoneVerification(input: RequestPhoneVerificationRequest, options?: RpcOptions): UnaryCall<RequestPhoneVerificationRequest, RequestPhoneVerificationResponse>;
    /**
     * @generated from protobuf rpc: VerifyPhone
     */
    verifyPhone(input: VerifyPhoneRequest, options?: RpcOptions): UnaryCall<VerifyPhoneRequest, VerifyPhoneResponse>;
    /**
     * 회원가입/로그인
     *
     * @generated from protobuf rpc: SignUp
     */
    signUp(input: SignUpRequest, options?: RpcOptions): UnaryCall<SignUpRequest, SignUpResponse>;
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse>;
    /**
     * @generated from protobuf rpc: SocialLogin
     */
    socialLogin(input: SocialLoginRequest, options?: RpcOptions): UnaryCall<SocialLoginRequest, SocialLoginResponse>;
    /**
     * 프로필
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse>;
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse>;
    /**
     * @generated from protobuf rpc: ChangePassword
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse>;
    /**
     * @generated from protobuf rpc: UpdateAvatar
     */
    updateAvatar(input: UpdateAvatarRequest, options?: RpcOptions): UnaryCall<UpdateAvatarRequest, UpdateAvatarResponse>;
    /**
     * 유저 검색(username 또는 nickname)
     *
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse>;
}
/**
 * ====== 서비스 정의 (명세)======
 *
 * @generated from protobuf service user.v1.UserService
 */
export class UserServiceClient implements IUserServiceClient, ServiceInfo {
    typeName = UserService.typeName;
    methods = UserService.methods;
    options = UserService.options;
    constructor(private readonly _transport: RpcTransport) {
    }
    /**
     * 중복/인증
     *
     * @generated from protobuf rpc: CheckUsername
     */
    checkUsername(input: CheckUsernameRequest, options?: RpcOptions): UnaryCall<CheckUsernameRequest, CheckUsernameResponse> {
        const method = this.methods[0], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckUsernameRequest, CheckUsernameResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: CheckEmail
     */
    checkEmail(input: CheckEmailRequest, options?: RpcOptions): UnaryCall<CheckEmailRequest, CheckEmailResponse> {
        const method = this.methods[1], opt = this._transport.mergeOptions(options);
        return stackIntercept<CheckEmailRequest, CheckEmailResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: RequestPhoneVerification
     */
    requestPhoneVerification(input: RequestPhoneVerificationRequest, options?: RpcOptions): UnaryCall<RequestPhoneVerificationRequest, RequestPhoneVerificationResponse> {
        const method = this.methods[2], opt = this._transport.mergeOptions(options);
        return stackIntercept<RequestPhoneVerificationRequest, RequestPhoneVerificationResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: VerifyPhone
     */
    verifyPhone(input: VerifyPhoneRequest, options?: RpcOptions): UnaryCall<VerifyPhoneRequest, VerifyPhoneResponse> {
        const method = this.methods[3], opt = this._transport.mergeOptions(options);
        return stackIntercept<VerifyPhoneRequest, VerifyPhoneResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 회원가입/로그인
     *
     * @generated from protobuf rpc: SignUp
     */
    signUp(input: SignUpRequest, options?: RpcOptions): UnaryCall<SignUpRequest, SignUpResponse> {
        const method = this.methods[4], opt = this._transport.mergeOptions(options);
        return stackIntercept<SignUpRequest, SignUpResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: Login
     */
    login(input: LoginRequest, options?: RpcOptions): UnaryCall<LoginRequest, LoginResponse> {
        const method = this.methods[5], opt = this._transport.mergeOptions(options);
        return stackIntercept<LoginRequest, LoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: SocialLogin
     */
    socialLogin(input: SocialLoginRequest, options?: RpcOptions): UnaryCall<SocialLoginRequest, SocialLoginResponse> {
        const method = this.methods[6], opt = this._transport.mergeOptions(options);
        return stackIntercept<SocialLoginRequest, SocialLoginResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 프로필
     *
     * @generated from protobuf rpc: GetProfile
     */
    getProfile(input: GetProfileRequest, options?: RpcOptions): UnaryCall<GetProfileRequest, GetProfileResponse> {
        const method = this.methods[7], opt = this._transport.mergeOptions(options);
        return stackIntercept<GetProfileRequest, GetProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateProfile
     */
    updateProfile(input: UpdateProfileRequest, options?: RpcOptions): UnaryCall<UpdateProfileRequest, UpdateProfileResponse> {
        const method = this.methods[8], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateProfileRequest, UpdateProfileResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: ChangePassword
     */
    changePassword(input: ChangePasswordRequest, options?: RpcOptions): UnaryCall<ChangePasswordRequest, ChangePasswordResponse> {
        const method = this.methods[9], opt = this._transport.mergeOptions(options);
        return stackIntercept<ChangePasswordRequest, ChangePasswordResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * @generated from protobuf rpc: UpdateAvatar
     */
    updateAvatar(input: UpdateAvatarRequest, options?: RpcOptions): UnaryCall<UpdateAvatarRequest, UpdateAvatarResponse> {
        const method = this.methods[10], opt = this._transport.mergeOptions(options);
        return stackIntercept<UpdateAvatarRequest, UpdateAvatarResponse>("unary", this._transport, method, opt, input);
    }
    /**
     * 유저 검색(username 또는 nickname)
     *
     * @generated from protobuf rpc: SearchUsers
     */
    searchUsers(input: SearchUsersRequest, options?: RpcOptions): UnaryCall<SearchUsersRequest, SearchUsersResponse> {
        const method = this.methods[11], opt = this._transport.mergeOptions(options);
        return stackIntercept<SearchUsersRequest, SearchUsersResponse>("unary", this._transport, method, opt, input);
    }
}
