/**
 * @fileoverview gRPC-Web generated client stub for user.v1
 * @enhanceable
 * @public
 */

// Code generated by protoc-gen-grpc-web. DO NOT EDIT.
// versions:
// 	protoc-gen-grpc-web v1.5.0
// 	protoc              v6.33.0
// source: user.proto


/* eslint-disable */
// @ts-nocheck



const grpc = {};
grpc.web = require('grpc-web');


var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js')
const proto = {};
proto.user = {};
proto.user.v1 = require('./user_pb.js');

/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.v1.UserServiceClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @param {string} hostname
 * @param {?Object} credentials
 * @param {?grpc.web.ClientOptions} options
 * @constructor
 * @struct
 * @final
 */
proto.user.v1.UserServicePromiseClient =
    function(hostname, credentials, options) {
  if (!options) options = {};
  options.format = 'text';

  /**
   * @private @const {!grpc.web.GrpcWebClientBase} The client
   */
  this.client_ = new grpc.web.GrpcWebClientBase(options);

  /**
   * @private @const {string} The hostname
   */
  this.hostname_ = hostname.replace(/\/+$/, '');

};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.CheckUsernameRequest,
 *   !proto.user.v1.CheckUsernameResponse>}
 */
const methodDescriptor_UserService_CheckUsername = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/CheckUsername',
  grpc.web.MethodType.UNARY,
  proto.user.v1.CheckUsernameRequest,
  proto.user.v1.CheckUsernameResponse,
  /**
   * @param {!proto.user.v1.CheckUsernameRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.CheckUsernameResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.CheckUsernameRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.CheckUsernameResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.CheckUsernameResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.checkUsername =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/CheckUsername',
      request,
      metadata || {},
      methodDescriptor_UserService_CheckUsername,
      callback);
};


/**
 * @param {!proto.user.v1.CheckUsernameRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.CheckUsernameResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.checkUsername =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/CheckUsername',
      request,
      metadata || {},
      methodDescriptor_UserService_CheckUsername);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.CheckEmailRequest,
 *   !proto.user.v1.CheckEmailResponse>}
 */
const methodDescriptor_UserService_CheckEmail = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/CheckEmail',
  grpc.web.MethodType.UNARY,
  proto.user.v1.CheckEmailRequest,
  proto.user.v1.CheckEmailResponse,
  /**
   * @param {!proto.user.v1.CheckEmailRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.CheckEmailResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.CheckEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.CheckEmailResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.CheckEmailResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.checkEmail =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/CheckEmail',
      request,
      metadata || {},
      methodDescriptor_UserService_CheckEmail,
      callback);
};


/**
 * @param {!proto.user.v1.CheckEmailRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.CheckEmailResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.checkEmail =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/CheckEmail',
      request,
      metadata || {},
      methodDescriptor_UserService_CheckEmail);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.RequestPhoneVerificationRequest,
 *   !proto.user.v1.RequestPhoneVerificationResponse>}
 */
const methodDescriptor_UserService_RequestPhoneVerification = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/RequestPhoneVerification',
  grpc.web.MethodType.UNARY,
  proto.user.v1.RequestPhoneVerificationRequest,
  proto.user.v1.RequestPhoneVerificationResponse,
  /**
   * @param {!proto.user.v1.RequestPhoneVerificationRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.RequestPhoneVerificationResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.RequestPhoneVerificationRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.RequestPhoneVerificationResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.RequestPhoneVerificationResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.requestPhoneVerification =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/RequestPhoneVerification',
      request,
      metadata || {},
      methodDescriptor_UserService_RequestPhoneVerification,
      callback);
};


/**
 * @param {!proto.user.v1.RequestPhoneVerificationRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.RequestPhoneVerificationResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.requestPhoneVerification =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/RequestPhoneVerification',
      request,
      metadata || {},
      methodDescriptor_UserService_RequestPhoneVerification);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.VerifyPhoneRequest,
 *   !proto.user.v1.VerifyPhoneResponse>}
 */
const methodDescriptor_UserService_VerifyPhone = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/VerifyPhone',
  grpc.web.MethodType.UNARY,
  proto.user.v1.VerifyPhoneRequest,
  proto.user.v1.VerifyPhoneResponse,
  /**
   * @param {!proto.user.v1.VerifyPhoneRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.VerifyPhoneResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.VerifyPhoneRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.VerifyPhoneResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.VerifyPhoneResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.verifyPhone =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/VerifyPhone',
      request,
      metadata || {},
      methodDescriptor_UserService_VerifyPhone,
      callback);
};


/**
 * @param {!proto.user.v1.VerifyPhoneRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.VerifyPhoneResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.verifyPhone =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/VerifyPhone',
      request,
      metadata || {},
      methodDescriptor_UserService_VerifyPhone);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.SignUpRequest,
 *   !proto.user.v1.SignUpResponse>}
 */
const methodDescriptor_UserService_SignUp = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/SignUp',
  grpc.web.MethodType.UNARY,
  proto.user.v1.SignUpRequest,
  proto.user.v1.SignUpResponse,
  /**
   * @param {!proto.user.v1.SignUpRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.SignUpResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.SignUpResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.SignUpResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.signUp =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/SignUp',
      request,
      metadata || {},
      methodDescriptor_UserService_SignUp,
      callback);
};


/**
 * @param {!proto.user.v1.SignUpRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.SignUpResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.signUp =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/SignUp',
      request,
      metadata || {},
      methodDescriptor_UserService_SignUp);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.LoginRequest,
 *   !proto.user.v1.LoginResponse>}
 */
const methodDescriptor_UserService_Login = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/Login',
  grpc.web.MethodType.UNARY,
  proto.user.v1.LoginRequest,
  proto.user.v1.LoginResponse,
  /**
   * @param {!proto.user.v1.LoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.LoginResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.LoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.LoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.login =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login,
      callback);
};


/**
 * @param {!proto.user.v1.LoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.LoginResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.login =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/Login',
      request,
      metadata || {},
      methodDescriptor_UserService_Login);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.SocialLoginRequest,
 *   !proto.user.v1.SocialLoginResponse>}
 */
const methodDescriptor_UserService_SocialLogin = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/SocialLogin',
  grpc.web.MethodType.UNARY,
  proto.user.v1.SocialLoginRequest,
  proto.user.v1.SocialLoginResponse,
  /**
   * @param {!proto.user.v1.SocialLoginRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.SocialLoginResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.SocialLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.SocialLoginResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.SocialLoginResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.socialLogin =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/SocialLogin',
      request,
      metadata || {},
      methodDescriptor_UserService_SocialLogin,
      callback);
};


/**
 * @param {!proto.user.v1.SocialLoginRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.SocialLoginResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.socialLogin =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/SocialLogin',
      request,
      metadata || {},
      methodDescriptor_UserService_SocialLogin);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.GetProfileRequest,
 *   !proto.user.v1.GetProfileResponse>}
 */
const methodDescriptor_UserService_GetProfile = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/GetProfile',
  grpc.web.MethodType.UNARY,
  proto.user.v1.GetProfileRequest,
  proto.user.v1.GetProfileResponse,
  /**
   * @param {!proto.user.v1.GetProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.GetProfileResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.GetProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.GetProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.GetProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.getProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_GetProfile,
      callback);
};


/**
 * @param {!proto.user.v1.GetProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.GetProfileResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.getProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/GetProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_GetProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.UpdateProfileRequest,
 *   !proto.user.v1.UpdateProfileResponse>}
 */
const methodDescriptor_UserService_UpdateProfile = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/UpdateProfile',
  grpc.web.MethodType.UNARY,
  proto.user.v1.UpdateProfileRequest,
  proto.user.v1.UpdateProfileResponse,
  /**
   * @param {!proto.user.v1.UpdateProfileRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.UpdateProfileResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.UpdateProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.UpdateProfileResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.UpdateProfileResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.updateProfile =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/UpdateProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateProfile,
      callback);
};


/**
 * @param {!proto.user.v1.UpdateProfileRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.UpdateProfileResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.updateProfile =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/UpdateProfile',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateProfile);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.ChangePasswordRequest,
 *   !proto.user.v1.ChangePasswordResponse>}
 */
const methodDescriptor_UserService_ChangePassword = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/ChangePassword',
  grpc.web.MethodType.UNARY,
  proto.user.v1.ChangePasswordRequest,
  proto.user.v1.ChangePasswordResponse,
  /**
   * @param {!proto.user.v1.ChangePasswordRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.ChangePasswordResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.ChangePasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.ChangePasswordResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.ChangePasswordResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.changePassword =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/ChangePassword',
      request,
      metadata || {},
      methodDescriptor_UserService_ChangePassword,
      callback);
};


/**
 * @param {!proto.user.v1.ChangePasswordRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.ChangePasswordResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.changePassword =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/ChangePassword',
      request,
      metadata || {},
      methodDescriptor_UserService_ChangePassword);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.UpdateAvatarRequest,
 *   !proto.user.v1.UpdateAvatarResponse>}
 */
const methodDescriptor_UserService_UpdateAvatar = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/UpdateAvatar',
  grpc.web.MethodType.UNARY,
  proto.user.v1.UpdateAvatarRequest,
  proto.user.v1.UpdateAvatarResponse,
  /**
   * @param {!proto.user.v1.UpdateAvatarRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.UpdateAvatarResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.UpdateAvatarRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.UpdateAvatarResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.UpdateAvatarResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.updateAvatar =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/UpdateAvatar',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateAvatar,
      callback);
};


/**
 * @param {!proto.user.v1.UpdateAvatarRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.UpdateAvatarResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.updateAvatar =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/UpdateAvatar',
      request,
      metadata || {},
      methodDescriptor_UserService_UpdateAvatar);
};


/**
 * @const
 * @type {!grpc.web.MethodDescriptor<
 *   !proto.user.v1.SearchUsersRequest,
 *   !proto.user.v1.SearchUsersResponse>}
 */
const methodDescriptor_UserService_SearchUsers = new grpc.web.MethodDescriptor(
  '/user.v1.UserService/SearchUsers',
  grpc.web.MethodType.UNARY,
  proto.user.v1.SearchUsersRequest,
  proto.user.v1.SearchUsersResponse,
  /**
   * @param {!proto.user.v1.SearchUsersRequest} request
   * @return {!Uint8Array}
   */
  function(request) {
    return request.serializeBinary();
  },
  proto.user.v1.SearchUsersResponse.deserializeBinary
);


/**
 * @param {!proto.user.v1.SearchUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>} metadata User defined
 *     call metadata
 * @param {function(?grpc.web.RpcError, ?proto.user.v1.SearchUsersResponse)}
 *     callback The callback function(error, response)
 * @return {!grpc.web.ClientReadableStream<!proto.user.v1.SearchUsersResponse>|undefined}
 *     The XHR Node Readable Stream
 */
proto.user.v1.UserServiceClient.prototype.searchUsers =
    function(request, metadata, callback) {
  return this.client_.rpcCall(this.hostname_ +
      '/user.v1.UserService/SearchUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_SearchUsers,
      callback);
};


/**
 * @param {!proto.user.v1.SearchUsersRequest} request The
 *     request proto
 * @param {?Object<string, string>=} metadata User defined
 *     call metadata
 * @return {!Promise<!proto.user.v1.SearchUsersResponse>}
 *     Promise that resolves to the response
 */
proto.user.v1.UserServicePromiseClient.prototype.searchUsers =
    function(request, metadata) {
  return this.client_.unaryCall(this.hostname_ +
      '/user.v1.UserService/SearchUsers',
      request,
      metadata || {},
      methodDescriptor_UserService_SearchUsers);
};


module.exports = proto.user.v1;

